// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: base/types/gfsperrors/error.proto

package gfsperrors

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GfSpError struct {
	CodeSpace      string `protobuf:"bytes,1,opt,name=code_space,json=codeSpace,proto3" json:"code_space,omitempty"`
	HttpStatusCode int32  `protobuf:"varint,2,opt,name=http_status_code,json=httpStatusCode,proto3" json:"http_status_code,omitempty"`
	InnerCode      int32  `protobuf:"varint,3,opt,name=inner_code,json=innerCode,proto3" json:"inner_code,omitempty"`
	Description    string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *GfSpError) Reset()         { *m = GfSpError{} }
func (m *GfSpError) String() string { return proto.CompactTextString(m) }
func (*GfSpError) ProtoMessage()    {}
func (*GfSpError) Descriptor() ([]byte, []int) {
	return fileDescriptor_a83019dca109f889, []int{0}
}
func (m *GfSpError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpError.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpError.Merge(m, src)
}
func (m *GfSpError) XXX_Size() int {
	return m.Size()
}
func (m *GfSpError) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpError.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpError proto.InternalMessageInfo

func (m *GfSpError) GetCodeSpace() string {
	if m != nil {
		return m.CodeSpace
	}
	return ""
}

func (m *GfSpError) GetHttpStatusCode() int32 {
	if m != nil {
		return m.HttpStatusCode
	}
	return 0
}

func (m *GfSpError) GetInnerCode() int32 {
	if m != nil {
		return m.InnerCode
	}
	return 0
}

func (m *GfSpError) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*GfSpError)(nil), "base.types.gfsperrors.GfSpError")
}

func init() { proto.RegisterFile("base/types/gfsperrors/error.proto", fileDescriptor_a83019dca109f889) }

var fileDescriptor_a83019dca109f889 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4e, 0xec, 0x30,
	0x10, 0x86, 0xe3, 0xf7, 0x00, 0x29, 0x46, 0x42, 0x28, 0x12, 0x52, 0x1a, 0xac, 0x40, 0x95, 0x66,
	0xe3, 0x82, 0x1b, 0x80, 0x16, 0x2a, 0x9a, 0x4d, 0x47, 0x13, 0x39, 0xf6, 0x6c, 0xd6, 0xc5, 0x66,
	0x2c, 0x7b, 0x82, 0xc4, 0x2d, 0x68, 0xb8, 0x13, 0xe5, 0x96, 0x94, 0x28, 0xb9, 0x08, 0xb2, 0x29,
	0xa0, 0xa0, 0xb2, 0xfc, 0xfd, 0xdf, 0xcc, 0x48, 0x3f, 0xbf, 0xea, 0x55, 0x00, 0x49, 0x2f, 0x0e,
	0x82, 0x1c, 0xb6, 0xc1, 0x81, 0xf7, 0xe8, 0x83, 0x4c, 0x4f, 0xe3, 0x3c, 0x12, 0x16, 0x17, 0x51,
	0x69, 0x92, 0xd2, 0xfc, 0x28, 0xd7, 0x6f, 0x8c, 0xe7, 0x0f, 0xdb, 0xd6, 0xad, 0xe3, 0xb7, 0xb8,
	0xe4, 0x5c, 0xa3, 0x81, 0x2e, 0x38, 0xa5, 0xa1, 0x64, 0x15, 0xab, 0xf3, 0x4d, 0x1e, 0x49, 0x1b,
	0x41, 0x51, 0xf3, 0xf3, 0x1d, 0x91, 0xeb, 0x02, 0x29, 0x9a, 0x42, 0x17, 0x83, 0xf2, 0x5f, 0xc5,
	0xea, 0xe3, 0xcd, 0x59, 0xe4, 0x6d, 0xc2, 0x77, 0x68, 0x20, 0x2e, 0xb2, 0xe3, 0x08, 0xfe, 0xdb,
	0xf9, 0x9f, 0x9c, 0x3c, 0x91, 0x14, 0x57, 0xfc, 0xd4, 0x40, 0xd0, 0xde, 0x3a, 0xb2, 0x38, 0x96,
	0x47, 0xe9, 0xd0, 0x6f, 0x74, 0xdb, 0xbd, 0xcf, 0x82, 0x1d, 0x66, 0xc1, 0x3e, 0x67, 0xc1, 0x5e,
	0x17, 0x91, 0x1d, 0x16, 0x91, 0x7d, 0x2c, 0x22, 0x7b, 0x5a, 0x0f, 0x96, 0x76, 0x53, 0xdf, 0x68,
	0xdc, 0xcb, 0x47, 0xd4, 0xea, 0x1e, 0xa7, 0xd1, 0xa8, 0x38, 0x24, 0xf7, 0xa8, 0xd5, 0x2a, 0x10,
	0x7a, 0x35, 0xc0, 0xca, 0x79, 0x7c, 0xb6, 0x06, 0xbc, 0xfc, 0xb3, 0x9b, 0xfe, 0x24, 0xd5, 0x72,
	0xf3, 0x15, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xef, 0x82, 0x73, 0x3b, 0x01, 0x00, 0x00,
}

func (m *GfSpError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintError(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if m.InnerCode != 0 {
		i = encodeVarintError(dAtA, i, uint64(m.InnerCode))
		i--
		dAtA[i] = 0x18
	}
	if m.HttpStatusCode != 0 {
		i = encodeVarintError(dAtA, i, uint64(m.HttpStatusCode))
		i--
		dAtA[i] = 0x10
	}
	if len(m.CodeSpace) > 0 {
		i -= len(m.CodeSpace)
		copy(dAtA[i:], m.CodeSpace)
		i = encodeVarintError(dAtA, i, uint64(len(m.CodeSpace)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintError(dAtA []byte, offset int, v uint64) int {
	offset -= sovError(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GfSpError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CodeSpace)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	if m.HttpStatusCode != 0 {
		n += 1 + sovError(uint64(m.HttpStatusCode))
	}
	if m.InnerCode != 0 {
		n += 1 + sovError(uint64(m.InnerCode))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	return n
}

func sovError(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozError(x uint64) (n int) {
	return sovError(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GfSpError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowError
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeSpace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeSpace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HttpStatusCode", wireType)
			}
			m.HttpStatusCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HttpStatusCode |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InnerCode", wireType)
			}
			m.InnerCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InnerCode |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipError(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthError
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipError(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowError
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowError
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowError
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthError
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupError
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthError
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthError        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowError          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupError = fmt.Errorf("proto: unexpected end of group")
)
