# This file configures github.com/golangci/golangci-lint.

run:
  concurrency: 4
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
#    - goconst
#    - errcheck
#    - depguard
#    - dogsled
#    - exportloopref
#    - gocritic
#    - gofumpt
#    - gosec
#    - nakedret
#    - nolintlint
#    - stylecheck
#    - typecheck
#    - goconst

linters-settings:
  gofmt:
    simplify: true
  staticcheck:
    checks:
      - '-SA1029'
