# This file configures github.com/golangci/golangci-lint.

run:
  concurrency: 4
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

linters-settings:
  staticcheck:
    checks:
      - '-SA1029'
