# This file configures github.com/golangci/golangci-lint.
version: "2"

run:
  concurrency: 4
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

  settings:
    staticcheck:
      checks:
        - '-SA1029'
