// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: base/types/gfspserver/rcmgr.proto

package gfspserver

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	gfsperrors "github.com/mocachain/moca-storage-provider/base/types/gfsperrors"
	gfsplimit "github.com/mocachain/moca-storage-provider/base/types/gfsplimit"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GfSpQueryResourceLimitRequest struct {
	Module []string `protobuf:"bytes,1,rep,name=module,proto3" json:"module,omitempty"`
}

func (m *GfSpQueryResourceLimitRequest) Reset()         { *m = GfSpQueryResourceLimitRequest{} }
func (m *GfSpQueryResourceLimitRequest) String() string { return proto.CompactTextString(m) }
func (*GfSpQueryResourceLimitRequest) ProtoMessage()    {}
func (*GfSpQueryResourceLimitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b3811ef695ee3f, []int{0}
}
func (m *GfSpQueryResourceLimitRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpQueryResourceLimitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpQueryResourceLimitRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpQueryResourceLimitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpQueryResourceLimitRequest.Merge(m, src)
}
func (m *GfSpQueryResourceLimitRequest) XXX_Size() int {
	return m.Size()
}
func (m *GfSpQueryResourceLimitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpQueryResourceLimitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpQueryResourceLimitRequest proto.InternalMessageInfo

func (m *GfSpQueryResourceLimitRequest) GetModule() []string {
	if m != nil {
		return m.Module
	}
	return nil
}

type GfSpQueryResourceLimitResponse struct {
	Err    *gfsperrors.GfSpError           `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Limits map[string]*gfsplimit.GfSpLimit `protobuf:"bytes,2,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *GfSpQueryResourceLimitResponse) Reset()         { *m = GfSpQueryResourceLimitResponse{} }
func (m *GfSpQueryResourceLimitResponse) String() string { return proto.CompactTextString(m) }
func (*GfSpQueryResourceLimitResponse) ProtoMessage()    {}
func (*GfSpQueryResourceLimitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b3811ef695ee3f, []int{1}
}
func (m *GfSpQueryResourceLimitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpQueryResourceLimitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpQueryResourceLimitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpQueryResourceLimitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpQueryResourceLimitResponse.Merge(m, src)
}
func (m *GfSpQueryResourceLimitResponse) XXX_Size() int {
	return m.Size()
}
func (m *GfSpQueryResourceLimitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpQueryResourceLimitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpQueryResourceLimitResponse proto.InternalMessageInfo

func (m *GfSpQueryResourceLimitResponse) GetErr() *gfsperrors.GfSpError {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GfSpQueryResourceLimitResponse) GetLimits() map[string]*gfsplimit.GfSpLimit {
	if m != nil {
		return m.Limits
	}
	return nil
}

type GfSpSetResourceLimitRequest struct {
	Limits map[string]*gfsplimit.GfSpLimit `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *GfSpSetResourceLimitRequest) Reset()         { *m = GfSpSetResourceLimitRequest{} }
func (m *GfSpSetResourceLimitRequest) String() string { return proto.CompactTextString(m) }
func (*GfSpSetResourceLimitRequest) ProtoMessage()    {}
func (*GfSpSetResourceLimitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b3811ef695ee3f, []int{2}
}
func (m *GfSpSetResourceLimitRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpSetResourceLimitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpSetResourceLimitRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpSetResourceLimitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpSetResourceLimitRequest.Merge(m, src)
}
func (m *GfSpSetResourceLimitRequest) XXX_Size() int {
	return m.Size()
}
func (m *GfSpSetResourceLimitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpSetResourceLimitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpSetResourceLimitRequest proto.InternalMessageInfo

func (m *GfSpSetResourceLimitRequest) GetLimits() map[string]*gfsplimit.GfSpLimit {
	if m != nil {
		return m.Limits
	}
	return nil
}

type GfSpSetResourceLimitResponse struct {
	Err          *gfsperrors.GfSpError `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	SuccessLists []string              `protobuf:"bytes,2,rep,name=success_lists,json=successLists,proto3" json:"success_lists,omitempty"`
}

func (m *GfSpSetResourceLimitResponse) Reset()         { *m = GfSpSetResourceLimitResponse{} }
func (m *GfSpSetResourceLimitResponse) String() string { return proto.CompactTextString(m) }
func (*GfSpSetResourceLimitResponse) ProtoMessage()    {}
func (*GfSpSetResourceLimitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b3811ef695ee3f, []int{3}
}
func (m *GfSpSetResourceLimitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpSetResourceLimitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpSetResourceLimitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpSetResourceLimitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpSetResourceLimitResponse.Merge(m, src)
}
func (m *GfSpSetResourceLimitResponse) XXX_Size() int {
	return m.Size()
}
func (m *GfSpSetResourceLimitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpSetResourceLimitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpSetResourceLimitResponse proto.InternalMessageInfo

func (m *GfSpSetResourceLimitResponse) GetErr() *gfsperrors.GfSpError {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GfSpSetResourceLimitResponse) GetSuccessLists() []string {
	if m != nil {
		return m.SuccessLists
	}
	return nil
}

func init() {
	proto.RegisterType((*GfSpQueryResourceLimitRequest)(nil), "base.types.gfspserver.GfSpQueryResourceLimitRequest")
	proto.RegisterType((*GfSpQueryResourceLimitResponse)(nil), "base.types.gfspserver.GfSpQueryResourceLimitResponse")
	proto.RegisterMapType((map[string]*gfsplimit.GfSpLimit)(nil), "base.types.gfspserver.GfSpQueryResourceLimitResponse.LimitsEntry")
	proto.RegisterType((*GfSpSetResourceLimitRequest)(nil), "base.types.gfspserver.GfSpSetResourceLimitRequest")
	proto.RegisterMapType((map[string]*gfsplimit.GfSpLimit)(nil), "base.types.gfspserver.GfSpSetResourceLimitRequest.LimitsEntry")
	proto.RegisterType((*GfSpSetResourceLimitResponse)(nil), "base.types.gfspserver.GfSpSetResourceLimitResponse")
}

func init() { proto.RegisterFile("base/types/gfspserver/rcmgr.proto", fileDescriptor_12b3811ef695ee3f) }

var fileDescriptor_12b3811ef695ee3f = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0xce, 0xa4, 0x58, 0xe8, 0x54, 0x41, 0x46, 0x5d, 0x4a, 0xd5, 0x18, 0xe3, 0xa5, 0x97, 0x9d,
	0x40, 0xd6, 0x45, 0xf1, 0x20, 0x2a, 0x2c, 0x5e, 0xf6, 0x62, 0x0a, 0x82, 0xbd, 0x48, 0x9a, 0x7d,
	0xdb, 0x0d, 0x36, 0x9d, 0xf8, 0xde, 0xa4, 0xd2, 0xa3, 0x27, 0x0f, 0x5e, 0xfc, 0x1f, 0xfc, 0x67,
	0x3c, 0xae, 0x37, 0x8f, 0xd2, 0xfe, 0x23, 0x32, 0x33, 0xf5, 0x07, 0x25, 0x5b, 0xa8, 0x82, 0x97,
	0x64, 0xe6, 0xcd, 0xf7, 0xde, 0xf7, 0x7d, 0x6f, 0x1e, 0xc3, 0xef, 0x8e, 0x33, 0x82, 0x58, 0x2f,
	0x2a, 0xa0, 0x78, 0x72, 0x4a, 0x15, 0x01, 0xce, 0x01, 0x63, 0xcc, 0xcb, 0x09, 0xca, 0x0a, 0x95,
	0x56, 0xe2, 0x86, 0x81, 0x48, 0x0b, 0x91, 0xbf, 0x21, 0xfd, 0xcd, 0x4c, 0x40, 0x54, 0x48, 0xb1,
	0xfd, 0xb9, 0xcc, 0x7e, 0xb8, 0x01, 0x99, 0x16, 0x65, 0xa1, 0x63, 0xfb, 0x75, 0x88, 0xe8, 0x01,
	0xbf, 0xfd, 0xfc, 0x74, 0x58, 0xbd, 0xa8, 0x01, 0x17, 0x29, 0x90, 0xaa, 0x31, 0x87, 0x63, 0x73,
	0x9e, 0xc2, 0xdb, 0x1a, 0x48, 0x8b, 0x3d, 0xde, 0x2e, 0xd5, 0x49, 0x3d, 0x85, 0x1e, 0x0b, 0x5b,
	0x83, 0x4e, 0xba, 0xde, 0x45, 0x1f, 0x7d, 0x1e, 0x5c, 0x94, 0x49, 0x95, 0x9a, 0x11, 0x88, 0x84,
	0xb7, 0x00, 0xb1, 0xc7, 0x42, 0x36, 0xe8, 0x26, 0xa1, 0xdc, 0x70, 0xe1, 0xe4, 0x4a, 0x53, 0xe3,
	0xc8, 0x2c, 0x53, 0x03, 0x16, 0xaf, 0x78, 0xdb, 0xca, 0xa3, 0x9e, 0x1f, 0xb6, 0x06, 0xdd, 0xe4,
	0xa9, 0x6c, 0x34, 0x2f, 0xb7, 0x53, 0x4b, 0xbb, 0xa3, 0xa3, 0x99, 0xc6, 0x45, 0xba, 0x2e, 0xd8,
	0x1f, 0xf1, 0xee, 0x1f, 0x61, 0x71, 0x95, 0xb7, 0xde, 0xc0, 0xc2, 0xaa, 0xeb, 0xa4, 0x66, 0x29,
	0x0e, 0xf9, 0xa5, 0x79, 0x36, 0xad, 0xa1, 0xe7, 0x5b, 0xc5, 0x77, 0x36, 0xa9, 0x5d, 0xdf, 0x0c,
	0xb3, 0x23, 0x73, 0xe8, 0x47, 0xfe, 0x43, 0x16, 0x7d, 0x65, 0xfc, 0xa6, 0x39, 0x18, 0x82, 0x6e,
	0xec, 0xe2, 0xcb, 0x5f, 0xb6, 0x98, 0xb5, 0xf5, 0x78, 0x8b, 0xad, 0x0b, 0x6a, 0xfc, 0x77, 0x4f,
	0xef, 0xf8, 0xad, 0x66, 0x39, 0xff, 0x70, 0xbd, 0xf7, 0xf8, 0x15, 0xaa, 0xf3, 0x1c, 0x88, 0x5e,
	0x4f, 0x0b, 0x5a, 0xdf, 0x72, 0x27, 0xbd, 0xbc, 0x0e, 0x1e, 0x9b, 0x58, 0xf2, 0xd9, 0xe7, 0xd7,
	0x4c, 0xde, 0x4f, 0xda, 0x21, 0xe0, 0xbc, 0xc8, 0x41, 0xbc, 0x67, 0xfc, 0x7a, 0x93, 0x22, 0x91,
	0xec, 0xde, 0xcd, 0xfe, 0xc1, 0x4e, 0x39, 0xce, 0x72, 0xe4, 0x89, 0x0f, 0x8c, 0xef, 0x35, 0xcf,
	0x9e, 0xb8, 0xbf, 0xe3, 0xa8, 0x3a, 0x1d, 0x87, 0x7f, 0x35, 0xe0, 0x91, 0xf7, 0x6c, 0xf4, 0x65,
	0x19, 0xb0, 0xf3, 0x65, 0xc0, 0xbe, 0x2f, 0x03, 0xf6, 0x69, 0x15, 0x78, 0xe7, 0xab, 0xc0, 0xfb,
	0xb6, 0x0a, 0xbc, 0xd1, 0x93, 0x49, 0xa1, 0xcf, 0xea, 0xb1, 0xcc, 0x55, 0x19, 0x97, 0x2a, 0xcf,
	0xf2, 0xb3, 0xac, 0x98, 0xd9, 0xd5, 0x3e, 0x69, 0x85, 0xd9, 0x04, 0xf6, 0x2b, 0x54, 0xf3, 0xe2,
	0x04, 0x30, 0x6e, 0x7c, 0x7d, 0xc6, 0x6d, 0xfb, 0x38, 0x1c, 0xfc, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x63, 0x9e, 0x8c, 0x0b, 0x9d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GfSpResourceServiceClient is the client API for GfSpResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GfSpResourceServiceClient interface {
	GfSpSetResourceLimit(ctx context.Context, in *GfSpSetResourceLimitRequest, opts ...grpc.CallOption) (*GfSpSetResourceLimitResponse, error)
	GfSpQueryResourceLimit(ctx context.Context, in *GfSpQueryResourceLimitRequest, opts ...grpc.CallOption) (*GfSpQueryResourceLimitResponse, error)
}

type gfSpResourceServiceClient struct {
	cc grpc1.ClientConn
}

func NewGfSpResourceServiceClient(cc grpc1.ClientConn) GfSpResourceServiceClient {
	return &gfSpResourceServiceClient{cc}
}

func (c *gfSpResourceServiceClient) GfSpSetResourceLimit(ctx context.Context, in *GfSpSetResourceLimitRequest, opts ...grpc.CallOption) (*GfSpSetResourceLimitResponse, error) {
	out := new(GfSpSetResourceLimitResponse)
	err := c.cc.Invoke(ctx, "/base.types.gfspserver.GfSpResourceService/GfSpSetResourceLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gfSpResourceServiceClient) GfSpQueryResourceLimit(ctx context.Context, in *GfSpQueryResourceLimitRequest, opts ...grpc.CallOption) (*GfSpQueryResourceLimitResponse, error) {
	out := new(GfSpQueryResourceLimitResponse)
	err := c.cc.Invoke(ctx, "/base.types.gfspserver.GfSpResourceService/GfSpQueryResourceLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GfSpResourceServiceServer is the server API for GfSpResourceService service.
type GfSpResourceServiceServer interface {
	GfSpSetResourceLimit(context.Context, *GfSpSetResourceLimitRequest) (*GfSpSetResourceLimitResponse, error)
	GfSpQueryResourceLimit(context.Context, *GfSpQueryResourceLimitRequest) (*GfSpQueryResourceLimitResponse, error)
}

// UnimplementedGfSpResourceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGfSpResourceServiceServer struct {
}

func (*UnimplementedGfSpResourceServiceServer) GfSpSetResourceLimit(ctx context.Context, req *GfSpSetResourceLimitRequest) (*GfSpSetResourceLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GfSpSetResourceLimit not implemented")
}
func (*UnimplementedGfSpResourceServiceServer) GfSpQueryResourceLimit(ctx context.Context, req *GfSpQueryResourceLimitRequest) (*GfSpQueryResourceLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GfSpQueryResourceLimit not implemented")
}

func RegisterGfSpResourceServiceServer(s grpc1.Server, srv GfSpResourceServiceServer) {
	s.RegisterService(&_GfSpResourceService_serviceDesc, srv)
}

func _GfSpResourceService_GfSpSetResourceLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GfSpSetResourceLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GfSpResourceServiceServer).GfSpSetResourceLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.types.gfspserver.GfSpResourceService/GfSpSetResourceLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GfSpResourceServiceServer).GfSpSetResourceLimit(ctx, req.(*GfSpSetResourceLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GfSpResourceService_GfSpQueryResourceLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GfSpQueryResourceLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GfSpResourceServiceServer).GfSpQueryResourceLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.types.gfspserver.GfSpResourceService/GfSpQueryResourceLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GfSpResourceServiceServer).GfSpQueryResourceLimit(ctx, req.(*GfSpQueryResourceLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var GfSpResourceService_serviceDesc = _GfSpResourceService_serviceDesc
var _GfSpResourceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "base.types.gfspserver.GfSpResourceService",
	HandlerType: (*GfSpResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GfSpSetResourceLimit",
			Handler:    _GfSpResourceService_GfSpSetResourceLimit_Handler,
		},
		{
			MethodName: "GfSpQueryResourceLimit",
			Handler:    _GfSpResourceService_GfSpQueryResourceLimit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/types/gfspserver/rcmgr.proto",
}

func (m *GfSpQueryResourceLimitRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpQueryResourceLimitRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpQueryResourceLimitRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Module) > 0 {
		for iNdEx := len(m.Module) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Module[iNdEx])
			copy(dAtA[i:], m.Module[iNdEx])
			i = encodeVarintRcmgr(dAtA, i, uint64(len(m.Module[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GfSpQueryResourceLimitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpQueryResourceLimitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpQueryResourceLimitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Limits) > 0 {
		for k := range m.Limits {
			v := m.Limits[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintRcmgr(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintRcmgr(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintRcmgr(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Err != nil {
		{
			size, err := m.Err.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRcmgr(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GfSpSetResourceLimitRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpSetResourceLimitRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpSetResourceLimitRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Limits) > 0 {
		for k := range m.Limits {
			v := m.Limits[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintRcmgr(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintRcmgr(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintRcmgr(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GfSpSetResourceLimitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpSetResourceLimitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpSetResourceLimitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SuccessLists) > 0 {
		for iNdEx := len(m.SuccessLists) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SuccessLists[iNdEx])
			copy(dAtA[i:], m.SuccessLists[iNdEx])
			i = encodeVarintRcmgr(dAtA, i, uint64(len(m.SuccessLists[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Err != nil {
		{
			size, err := m.Err.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRcmgr(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRcmgr(dAtA []byte, offset int, v uint64) int {
	offset -= sovRcmgr(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GfSpQueryResourceLimitRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Module) > 0 {
		for _, s := range m.Module {
			l = len(s)
			n += 1 + l + sovRcmgr(uint64(l))
		}
	}
	return n
}

func (m *GfSpQueryResourceLimitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Err != nil {
		l = m.Err.Size()
		n += 1 + l + sovRcmgr(uint64(l))
	}
	if len(m.Limits) > 0 {
		for k, v := range m.Limits {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovRcmgr(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovRcmgr(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovRcmgr(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *GfSpSetResourceLimitRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Limits) > 0 {
		for k, v := range m.Limits {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovRcmgr(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovRcmgr(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovRcmgr(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *GfSpSetResourceLimitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Err != nil {
		l = m.Err.Size()
		n += 1 + l + sovRcmgr(uint64(l))
	}
	if len(m.SuccessLists) > 0 {
		for _, s := range m.SuccessLists {
			l = len(s)
			n += 1 + l + sovRcmgr(uint64(l))
		}
	}
	return n
}

func sovRcmgr(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRcmgr(x uint64) (n int) {
	return sovRcmgr(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GfSpQueryResourceLimitRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRcmgr
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpQueryResourceLimitRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpQueryResourceLimitRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRcmgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRcmgr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRcmgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = append(m.Module, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRcmgr(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRcmgr
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GfSpQueryResourceLimitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRcmgr
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpQueryResourceLimitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpQueryResourceLimitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRcmgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRcmgr
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRcmgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Err == nil {
				m.Err = &gfsperrors.GfSpError{}
			}
			if err := m.Err.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRcmgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRcmgr
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRcmgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Limits == nil {
				m.Limits = make(map[string]*gfsplimit.GfSpLimit)
			}
			var mapkey string
			var mapvalue *gfsplimit.GfSpLimit
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRcmgr
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRcmgr
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthRcmgr
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthRcmgr
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRcmgr
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthRcmgr
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthRcmgr
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &gfsplimit.GfSpLimit{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipRcmgr(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthRcmgr
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Limits[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRcmgr(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRcmgr
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GfSpSetResourceLimitRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRcmgr
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpSetResourceLimitRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpSetResourceLimitRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRcmgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRcmgr
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRcmgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Limits == nil {
				m.Limits = make(map[string]*gfsplimit.GfSpLimit)
			}
			var mapkey string
			var mapvalue *gfsplimit.GfSpLimit
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRcmgr
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRcmgr
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthRcmgr
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthRcmgr
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRcmgr
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthRcmgr
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthRcmgr
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &gfsplimit.GfSpLimit{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipRcmgr(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthRcmgr
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Limits[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRcmgr(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRcmgr
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GfSpSetResourceLimitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRcmgr
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpSetResourceLimitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpSetResourceLimitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRcmgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRcmgr
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRcmgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Err == nil {
				m.Err = &gfsperrors.GfSpError{}
			}
			if err := m.Err.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SuccessLists", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRcmgr
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRcmgr
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRcmgr
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SuccessLists = append(m.SuccessLists, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRcmgr(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRcmgr
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRcmgr(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRcmgr
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRcmgr
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRcmgr
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRcmgr
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRcmgr
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRcmgr
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRcmgr        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRcmgr          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRcmgr = fmt.Errorf("proto: unexpected end of group")
)
